sver can't work with a path with trailing separator
mitoma/sver pull request #64
Opened 2022-11-09 07:02 UTC by kna

sver can't work properly with the followings cases.

I fixed it with removing it. This is my first time writing Rust. I'm not sure this PR is good in Rust..

## `sver list` can't list path with the separator at the end

```
# file structure
- lib1
  - sver.toml
- lib2
  - test2.txt
```

```
# lib1/sver.toml
[default]
dependencies = [
     "lib2/",
]
```

```
% sver list lib1
lib1/sver.toml # lib2/test2.txt should be included!
```

## `sver validate` reports that the test data of https://github.com/mitoma/sver/issues/62 is invalid

```
% sver validate   
[NG]	lib/sver.toml:[default]    # This should be valid!
		invalid_dependency:["lib/:prof1", "lib/:prof2"]
		invalid_exclude:[]
[OK]	lib/sver.toml:[prof1]
[OK]	lib/sver.toml:[prof2]
```

2022-11-09 15:15 UTC, mitoma requested changes
Thank you for your Pull Request.
If you can take the four suggestions, we can merge them.

2022-11-09 15:15 UTC, mitoma commented on src/lib.rs
>              caps.get(1).unwrap().as_str().to_string(),
diff-2
```suggestion
            canonicalize(caps.get(1).unwrap().as_str()).to_string(),
```

2022-11-09 15:15 UTC, mitoma commented on src/lib.rs
> +        );
add two test case.

```suggestion
        );
        assert_eq!(
            split_path_and_profile(":hello"),
            CalculationTarget::new("".to_string(), "hello".to_string())
        );
        assert_eq!(
            split_path_and_profile("/:hello"),
            CalculationTarget::new("".to_string(), "hello".to_string())
        );
```

2022-11-09 22:00 UTC, mitoma commented
Sorry. Previous review comment was not enough.
It seems that cli args and sver.toml must be parsed according to different rules.

Please wait while I sort it out.

2022-11-09 23:58 UTC, kna commented
@mitoma 
Thank you for your review and noticing other problems.
I'll check them.

Cloud you tell me one edge case?
If the expression is ``(empty string), how does it work?
It is valid(current directory) for cli args and invalid for sver.toml?
Or it is valid for sver.toml too?

2022-11-10 00:07 UTC, mitoma commented
I think the case goes like this.

| expression         | cli args | sver.toml               |
| ------------------ | -------- | ----------------------- |
| "" (empty)         | invalid  | valid ( ≒ `:default` )  |

2022-11-10 00:27 UTC, mitoma commented
@kna 
I fixed it another way. Can you please confirm?
https://github.com/mitoma/sver/tree/path_with_separator_at_end_2

2022-11-10 02:23 UTC, kna commented
@mitoma 
> https://github.com/mitoma/sver/tree/path_with_separator_at_end_2

It is perfect for me! Thank you. I'll close this PR.


By the way, sver works like this on https://github.com/mitoma/sver/tree/path_with_separator_at_end_2
expression | cli args | sver.toml
-- | -- | --
// | invalid | valid

(reason: `trim_end_matches` removes matched patterns repeatedly) 

I think it's okay to be an error if you deal strictly with it.
How do you think?

2022-11-10 11:23 UTC, mitoma commented
Thank you for your confirmation.
Multiple trailing slashes are removed on Linux, so I think this behavior is natural.

```bash
$ ls /tmp | sha256sum
a78ffd5c1ea0c6cd7812e5ddab3bb0f86df0fbf863fbf502df4e17ea0029688c  -
$ ls /tmp/ | sha256sum
a78ffd5c1ea0c6cd7812e5ddab3bb0f86df0fbf863fbf502df4e17ea0029688c  -
$ ls /tmp////// | sha256sum
a78ffd5c1ea0c6cd7812e5ddab3bb0f86df0fbf863fbf502df4e17ea0029688c  -
```

2022-11-10 23:36 UTC, kna commented
@mitoma 
I see. I agree with you!

2022-11-10 23:36 UTC, closed without merging